# Travis file for ROS2 Java.
# Version 2

sudo: required

language: generic

os:
  - linux

cache:
  directories:
    - .autoconf
    - $HOME/.m2
    - $HOME/.gradle

services:
  - docker

env:
  global:
    - HOME_BUILD=${HOME}/build
    - ROS2WS=${HOME_BUILD}/ros2_java_ws
    - PYTHON_PATH=/usr/bin/python3
    - COMMIT=${TRAVIS_COMMIT::8}
    - ENV_PATH=${HOME_BUILD}/.env

matrix:
  include:
    - os: linux
      env: DOCKER_DIST="debian"
      services:
        - docker
    - os: linux
      env: DOCKER_DIST="ubuntu"
      services:
        - docker
    - os: linux
      env: DOCKER_DIST="debian-stable"
      services:
        - docker
    - os: linux
      env: DOCKER_DIST="ubuntu-rolling"
      services:
        - docker
    - os: osx
      env:
        - PYTHON_PATH="/usr/local/opt/python3/bin/python3.6"
        - TRAVIS_OS_NAME="osx"
        - PKG_EXCLUDE="$PKG_EXCLUDE console_bridge orocos_kdl class_loader rosidl_generator_py pendulum_msgs rttest rclcpp dummy_map_server tf2 tf2_msgs tf2_ros tf2_eigen urdfdom_headers urdfdom urdf kdl_parser robot_state_publisher dummy_robot_bringup common_interfaces test_msgs dummy_sensors image_geometry sros2 test_security tf2_geometry_msgs nav_msgs actionlib_msgs diagnostic_msgs rcljava_utils rcl_lifecycle"
      osx_image: xcode9.1
  allow_failures:
    - env: DOCKER_DIST="debian-stable"
    - env: DOCKER_DIST="ubuntu-rolling"
    - os: osx

before_install:
  - ./scripts/travis-ci/${TRAVIS_OS_NAME}_prepare.sh

script:
  - ./scripts/travis-ci/${TRAVIS_OS_NAME}_run.sh

after_success:
  - ./scripts/travis-ci/${TRAVIS_OS_NAME}_success.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4aac82b42245203edceb
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
